scanner:
  # 扫描器基本配置
  port: 11434
  gateway_mac: ""  # 将自动获取 eth0 MAC 地址
  timeout: 3s
  max_workers: 200

  # 文件路径配置
  input_file: "ip.txt"
  output_file: "results.csv"

  # 性能测试配置
  bench:
    enabled: true
    prompt: "为什么太阳会发光？用一句话回答"
    timeout: 30s

  # Zmap配置
  zmap:
    threads: 10
    interface: "eth0"

  # Masscan配置
  masscan:
    rate: 1000
    interface: "eth0"

  # HTTP客户端配置
  http:
    max_idle_conns: 100
    idle_timeout: 90s

  # 进度保存配置
  state:
    file: "scan_state.json"
    save_interval: 30s
