FROM alpine:latest
ARG version=v2.2.1
ADD ./Releases/${version}/linux/ollama_scanner-linux-amd64 /usr/local/bin/ollama_scanner
RUN chmod +x /usr/local/bin/ollama_scanner

# 设置默认命令
CMD ["ollama_scanner"]