FROM docker.io/mongo:4.4.0 

ARG version=v2.2
# 复制 ollama_scanner 可执行文件
ADD ./Releases/${version}/linux/ollama_scanner_mongoDB-linux-arm64 /usr/local/bin/ollama_scanner
# 复制启动脚本
COPY start_v2.2.3.sh /start.sh
# 添加 MongoDB 官方仓库
RUN mkdir -p /var/log/mongodb /ollama_scanner/db /ollama_scanner/bin && \
    chown -R mongodb:mongodb /var/log/mongodb  && \
    chmod +x /usr/local/bin/ollama_scanner  && \
    chmod +x /start.sh  && \
    rm -rf /var/cache/apk/*

# 暴露 MongoDB 默认端口
EXPOSE 27017

# 设置启动脚本为入口点
ENTRYPOINT ["/start.sh"]
