FROM docker.io/arm64v8/alpine:latest
ARG version=v2.2
ADD ./Releases/${version}/ollama_scanner_zmap-linux-arm64 /usr/local/bin/ollama_scanner
RUN chmod +x /usr/local/bin/ollama_scanner

# 设置默认命令
CMD ["ollama_scanner"]